### ISSUE TITLE
Doesn't support Rails 4?

### ISSUE THREAD

**Issue by parkr** [ASCTech/shibboleth-rails#2]
Hi! I am putting together a Rails 4 application and wanted to use Shibboleth-rails. After v0.3.1, the gemspec requires Rails 3 (`~> 3`, to be precise). Can this be changed?

``` text
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    shibboleth-rails (~> 0.7.3) ruby depends on
      rails (~> 3.0) ruby

    rails (4.0.0)
```

Thanks!

**Comment by kyledecot** [comment]
Sorry @parkr. You'll want to use the rails4 branch in the meantime. At some point this will be merge into master.
